### ISSUE TITLE
RuntimeError: Lapack Error gesdd : 1 superdiagonals failed to converge.

### ISSUE THREAD

**Issue by raj-shah** [adavoudi/spdnet#9]
I get a RuntimeError when running `augment_data.py`, which traces back to SVD (`matrix_operator` function invoked from `tangent_space` function). Could this be because of a possible NaN in the tensor or just a badly-conditioned matrix?

```
Traceback (most recent call last):
  File "augment_data.py", line 35, in <module>
    tangent = tangent_space(data, data)
  File "/home/reddwarf/.local/lib/python3.6/site-packages/spdnet/utils.py", line 43, in tangent_space
    middle = matrix_operator(middle, 'expm')
  File "/home/reddwarf/.local/lib/python3.6/site-packages/spdnet/utils.py", line 20, in matrix_operator
    u, s, v = A.svd()
RuntimeError: Lapack Error gesdd : 1 superdiagonals failed to converge. at /opt/conda/conda-bld/pytorch_1556653183467/work/aten/src/TH/generic/THTensorLapack.cpp:406
```

**Comment by adavoudi** [comment]
I am not sure how to properly augment SPD matrices. This function was an idea that I thought might work. Do you have any idea?

**Comment by zhanghuayu-seu** [comment]
I have the same problem.
